---
- hosts: all
  become: true
  gather_facts: true
  ignore_errors: true
  vars:
    user_name: sylvie2004
    group_name: devops
  vars_files:
    - variables.yml
  tasks:
  - name: check the time
    command: date
#    when: ansible_distribution == "sylvie" or ansible_processor_nproc ==2
  - name: create user sylvie
    user:
       name: "{{user_name}}"
       comment: sylvie Admin
  - name: create group 
    group:
       name: "{{group_name}}"
       state: present
  - name: install package
    package: 
      name: "{{pkg_name}}"
      state: present     

