---
dependencies: []

galaxy_info:
  role_name: java
  author: sylvie
  description: Java for Linux
  company: DSG
  license: "license (BSD, MIT)"
  min_ansible_version: 2.10
  platforms:
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
        - buster
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
        - bionic
        - focal
        - jammy
    - name: FreeBSD
      versions:
        - 10.2
  galaxy_tags:
    - development
    - system
    - web
    - java
    - jdk
    - openjdk
    - oracle
